version: 2

jobs:
  build:
    docker:

      - image: circleci/node:9.3
        environment:
          - PORT: 3000
          - PGUSER: 'test'
          - PGPASSWORD: 'test'
          - PGDATABASE: 'test'
          - PGHOST: 'localhost'
          - PGPORT: '5432'
    
      - image: circleci/postgres:10.1
        environment:
          - POSTGRES_USER: test
          - POSTGRES_DB: test
          - POSTGRES_PASSWORD: test

      - image: davidqhr/0x-testrpc:latest

    steps:
      - checkout
      
      - run:
          name: Update NPM
          command: |
            npm install npm@latest
            sudo rm -rf /usr/local/lib/node_modules/npm
            sudo mv node_modules/npm /usr/local/lib/node_modules/npm
            sudo chown -R 500:500 /usr/local/lib/node_modules/npm
       

      - run:
          name: "Checking Versions"
          command: |
            node --version
            npm --version
      - run:
          name: Change permissions from root to user
          command: sudo chown -R $(whoami) $(npm config get prefix)/{lib/node_modules,bin,share}
          
      - run:
          name: npm install -g truffle
          command: npm install -g truffle
          
      - run:
          name: truffle init
          command: truffle init
          
      - run:
          name: truffle compile
          command: truffle compile
          
      - run:
          name: Test Packages
          command: npm uninstall truffle
